### ISSUE TITLE
Bug in visualize

### ISSUE THREAD

**Issue by zyb19960609** [quancore/social-lstm#22]
Traceback (most recent call last):
  File "/home/zly/data/zhangyanbo/social-lstm-master/validation.py", line 775, in <module>
    main()
  File "/home/zly/data/zhangyanbo/social-lstm-master/validation.py", line 765, in main
    args.max_ped_ratio, results[i][5], [min_r, max_r, plot_offset], 20)
  File "/home/zly/data/zhangyanbo/social-lstm-master/validation.py", line 410, in plot_trajectories
    colors, name, frames, true_target_id_values, plot_directory, style, num_of_color)
  File "/home/zly/data/zhangyanbo/social-lstm-master/validation.py", line 482, in create_plot_animation
    ani.save(plot_directory + '/' + name + '.mp4')
  File "/home/zly/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py", line 1200, in save
    writer.grab_frame(**savefig_kwargs)
  File "/home/zly/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/zly/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py", line 241, in saving
    self.finish()
  File "/home/zly/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py", line 367, in finish
    self.cleanup()
  File "/home/zly/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py", line 405, in cleanup
    out, err = self._proc.communicate()
  File "/home/zly/anaconda3/lib/python3.6/subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/zly/anaconda3/lib/python3.6/subprocess.py", line 1525, in _communicate
    selector.register(self.stdout, selectors.EVENT_READ)
  File "/home/zly/anaconda3/lib/python3.6/selectors.py", line 351, in register
    key = super().register(fileobj, events, data)
  File "/home/zly/anaconda3/lib/python3.6/selectors.py", line 237, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/home/zly/anaconda3/lib/python3.6/selectors.py", line 224, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/home/zly/anaconda3/lib/python3.6/selectors.py", line 39, in _fileobj_to_fd
    "{!r}".format(fileobj)) from None
ValueError: Invalid file object: <_io.BufferedReader name=9>

**Comment by quancore** [comment]
In the test environment, it was working. The error could be related to a version of a package. Feel free to submit a PR if needed.
