### ISSUE TITLE
Question about the datasets in the train folder

### ISSUE THREAD

**Issue by Joanne-PYL** [quancore/social-lstm#29]
Hi,
I want to implement my own data in your model, and I have a question about your dataset in the train folder. I noticed that in the biwi train folder, there are two files, biwi_hotel_0.txt and biwi_hotal.txt. I want to ask do they have any relationship? Since I found this relationship for your other datasets as well, and I am really confused. It would be really helpful for my project if you can answer me. Please let me know if I do not illustrate my question clearly. Thank you.

**Comment by quancore** [comment]
Detailed info about challange and datasets: https://www.aicrowd.com/challenges/trajnet-a-trajectory-forecasting-challenge

**Comment by Joanne-PYL** [comment]
Thank you for your reply and the link. After I read the link, just to be sure, I think biwi_hotel.txt is the real position for each pedestrian. However, I still cannot figure out what is biwi_hotel_0.txt., can you briefly explain the third and fourth column in biwi_hotel_0.txt file? Thank you.

**Comment by quancore** [comment]
Size of the matrix is 4 x numTrajectoryPoints

The first row contains all the frame numbers

The second row contains all the pedestrian IDs

The third row contains all the y-coordinates

The fourth row contains all the x-coordinates

BIWI dataset has been removed from ETH page but check here: https://riemenschneider.hayko.at/vision/dataset/task.php?did=106

**Comment by hxhily1999** [comment]
Traceback (most recent call last):
  File "D:/goole_download/social-lstm-master/social-lstm-master/train.py", line 626, in <module>
    main()
  File "D:/goole_download/social-lstm-master/social-lstm-master/train.py", line 94, in main
    train(args)
  File "D:/goole_download/social-lstm-master/social-lstm-master/train.py", line 214, in train
    dataset_data = dataloader.get_dataset_dimension(folder_name)
  File "D:\goole_download\social-lstm-master\social-lstm-master\utils.py", line 712, in get_dataset_dimension
    return self.dataset_dimensions[file_name]
KeyError: 'train'
I can't slove this bug in the train.py for a long time ,who can help me ?

**Comment by zkxwy1996** [comment]
> Traceback (most recent call last): File "D:/goole_download/social-lstm-master/social-lstm-master/train.py", line 626, in main() File "D:/goole_download/social-lstm-master/social-lstm-master/train.py", line 94, in main train(args) File "D:/goole_download/social-lstm-master/social-lstm-master/train.py", line 214, in train dataset_data = dataloader.get_dataset_dimension(folder_name) File "D:\goole_download\social-lstm-master\social-lstm-master\utils.py", line 712, in get_dataset_dimension return self.dataset_dimensions[file_name] KeyError: 'train' I can't slove this bug in the train.py for a long time ,who can help me ?

I have encountered the same problem. How did you solve it?

**Comment by LeeXiaosong** [comment]
> Hi, I want to implement my own data in your model, and I have a question about your dataset in the train folder. I noticed that in the biwi train folder, there are two files, biwi_hotel_0.txt and biwi_hotal.txt. I want to ask do they have any relationship? Since I found this relationship for your other datasets as well, and I am really confused. It would be really helpful for my project if you can answer me. Please let me know if I do not illustrate my question clearly. Thank you.

hi, I want to ask do you have save this question？ I also want to  implement my own data,  but now I have the same question about biwi_hotel_0.txt and biwi_hotal.txt. Can I train it only with biwi_hotal.txt. Thanks you.

**Comment by lizzzpeng** [comment]
> Thank you for your reply and the link. After I read the link, just to be sure, I think biwi_hotel.txt is the real position for each pedestrian. However, I still cannot figure out what is biwi_hotel_0.txt., can you briefly explain the third and fourth column in biwi_hotel_0.txt file? Thank you.

Hi,i wanna to use my own dataset in this model too. I have the same problem about hotel.txt/hotel_0.txt . I don't kown what means about two files.
