### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by Kamel-schbock** [quancore/social-lstm#31]
Hey,
I run training, test, validation successfully. But when i run visualize.py i got the following error: 
-----------------------------------------------------------------------------------------------------------------------------------
Video creation for  sequence00000  is starting...
MovieWriter ffmpeg unavailable; trying to use <class 'matplotlib.animation.PillowWriter'> instead.
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/site-packages/PIL/Image.py", line 2114, in save
    format = EXTENSION[ext]
KeyError: '.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "visualize.py", line 772, in <module>
    main()
  File "visualize.py", line 762, in main
    target_traj =  plot_trajectories(results[i][0], results[i][1], results[i][2], results[i][3],results[i][4], name, figure_save_directory, args.min_traj ,args.max_ped_ratio, results[i][5], [min_r, max_r, plot_offset], 20)
  File "visualize.py", line 413, in plot_trajectories
    create_plot_animation(plt, video_plot_trajs, processed_ped_index, target_id, real_inv_lookup, obs_length, markers, colors, name, frames, true_target_id_values, plot_directory, style, num_of_color)
  File "visualize.py", line 479, in create_plot_animation
    ani.save(plot_directory+'/'+name+'.mp4')
  File "/home/user/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 1156, in save
    writer.grab_frame(**savefig_kwargs)
  File "/home/user/anaconda3/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/user/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 232, in saving
    self.finish()
  File "/home/user/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 577, in finish
    duration=int(1000 / self.fps), loop=0)
  File "/home/user/anaconda3/lib/python3.7/site-packages/PIL/Image.py", line 2116, in save
    raise ValueError("unknown file extension: {}".format(ext))
ValueError: unknown file extension: .mp4
-----------------------------------------------------------------------------------------------------------------------------------
Can you please help me? 
Thanks

**Comment by quancore** [comment]
Please install ffmpeg.

**Comment by 396559551** [comment]
Can you copy your project for me? I can't run the original author's code。please~
