### ISSUE TITLE
cannot run it project,when i need "  subprocess.call([script_path])"  it will stop 

### ISSUE THREAD

**Issue by 15353519380** [quancore/social-lstm#44]
Directory creation script is running...
Traceback (most recent call last):
  File "D:/predictionProject/social-lstm/train.py", line 626, in <module>
    main()
  File "D:/predictionProject/social-lstm/train.py", line 94, in main
    train(args)
  File "D:/predictionProject/social-lstm/train.py", line 111, in train
    subprocess.call([f_prefix+'/make_directories.sh'])
  File "C:\Users\user\anaconda3\envs\DeepLearning\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\user\anaconda3\envs\DeepLearning\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\anaconda3\envs\DeepLearning\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by 15353519380** [comment]
i have fixed it ,thanks all.
